/**
 * List of all boss activities from the RuneScape API
 * This includes everything from "Abyssal Sire" onwards
 */
export const BOSS_ACTIVITIES = [
    'Abyssal Sire',
    'Alchemical Hydra',
    'Amoxliatl',
    'Araxxor',
    'Artio',
    'Barrows Chests',
    'Brutus',
    'Bryophyta',
    'Callisto',
    'Cal\'varion',
    'Cerberus',
    'Chambers of Xeric',
    'Chambers of Xeric: Challenge Mode',
    'Chaos Elemental',
    'Chaos Fanatic',
    'Commander Zilyana',
    'Corporeal Beast',
    'Crazy Archaeologist',
    'Dagannoth Prime',
    'Dagannoth Rex',
    'Dagannoth Supreme',
    'Deranged Archaeologist',
    'Doom of Mokhaiotl',
    'Duke Sucellus',
    'General Graardor',
    'Giant Mole',
    'Grotesque Guardians',
    'Hespori',
    'Kalphite Queen',
    'King Black Dragon',
    'Kraken',
    'Kree\'Arra',
    'K\'ril Tsutsaroth',
    'Lunar Chests',
    'Mimic',
    'Nex',
    'Nightmare',
    'Phosani\'s Nightmare',
    'Obor',
    'Phantom Muspah',
    'Sarachnis',
    'Scorpia',
    'Scurrius',
    'Shellbane Gryphon',
    'Skotizo',
    'Sol Heredit',
    'Spindel',
    'Tempoross',
    'The Gauntlet',
    'The Corrupted Gauntlet',
    'The Hueycoatl',
    'The Leviathan',
    'The Royal Titans',
    'The Whisperer',
    'Theatre of Blood',
    'Theatre of Blood: Hard Mode',
    'Thermonuclear Smoke Devil',
    'Tombs of Amascut',
    'Tombs of Amascut: Expert Mode',
    'TzKal-Zuk',
    'TzTok-Jad',
    'Vardorvis',
    'Venenatis',
    'Vet\'ion',
    'Vorkath',
    'Wintertodt',
    'Yama',
    'Zalcano',
    'Zulrah',
] as const;

/**
 * Check if an activity name is a boss activity
 */
export function isBossActivity(activityName: string): boolean {
    return BOSS_ACTIVITIES.includes(activityName as typeof BOSS_ACTIVITIES[number]);
}


